/****************************************************************************
 *
 *   Copyright (c) 2012-2019 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/**
 * @file ThrustEstimate.c
 * Application for estimating the thrust generated by each rotor.
 *
 * @author Davi Henrique <davihenriqueds@gmail.com>
 */

#include "ThrustEstimate.hpp"

ThrustEstimate::ThrustEstimate() :
	ModuleParams(nullptr),
	ScheduledWorkItem(MODULE_NAME, px4::wq_configurations::test1)
{
	c[0] = 0.0724;
	c[1] = 6.1490 * pow(10, -5);
	c[2] = 0.2993;
	c[3] = 1.2998 * pow(10,-8);
	c[4] = 0;

	d[0] = 4.2959;
	d[1] = -1.7154 * pow(10, 5);

	K_q[0] = 0.242;
	K_q[1] = 0.0014;

	// X250
	mass = 5 * pow(10, -3);
	radius = 6.5 * pow(10, -2);
	thrust_scale = 0.085896145;
	N_b = 3;

	// X500
	// mass = 14 * pow(10, -3);
	// radius = 16 * pow(10, -2);
	// thrust_scale = 1.575164103;
	// N_b = 2;

	rho = 1.293;
	Delta = pow(10, -1);
	N = 20;
	epsilon = pow(10, -5);
	initialize_parameters();
}

ThrustEstimate::~ThrustEstimate()
{
	perf_free(_loop_perf);
	perf_free(_loop_interval_perf);
}

bool ThrustEstimate::init()
{
	// execute Run() on every sensor_accel publication
	if (!_esc_status_sub.registerCallback()) {
		PX4_ERR("callback registration failed");
		return false;
	}

	// alternatively, Run on fixed interval
	// ScheduleOnInterval(5000_us); // 2000 us interval, 200 Hz rate

	return true;
}

void ThrustEstimate::Run()
{
	if (should_exit()) {
		ScheduleClear();
		exit_and_cleanup();
		return;
	}

	perf_begin(_loop_perf);
	perf_count(_loop_interval_perf);

	// Check if parameters have changed
	if (_vehicle_odom_sub.updated()) {
		vehicle_odometry_s odom;
		_vehicle_odom_sub.copy(&odom);

		// Body frame to local frame
		const matrix::Dcmf R_body_to_local(matrix::Quatf(odom.q));

		// Rotate linear velocity from local to body frame
		const matrix::Vector3f linvel_body(R_body_to_local.transpose() * matrix::Vector3f(odom.vx, odom.vy, odom.vz));

		_vx = double(linvel_body(0));
		_vy = double(linvel_body(1));

		// vehicle_linear_velocity_s data;
		// data.timestamp = hrt_absolute_time();
		// data.xyz[0] = linvel_body(0);
		// data.xyz[1] = linvel_body(1);
		// data.xyz[2] = linvel_body(2);
		// _linear_velocity_pub.publish(data);
	}

	// Check if parameters have changed
	if (_esc_status_sub.updated()) {
		_begin_all = hrt_absolute_time();
		// clear update
		esc_status_s esc;
		_esc_status_sub.copy(&esc);

		for(int j = 0; j < 4; j++){
			old_thrust[j] = thrust[j];
			w_old[j] = w[j];

			// now[j] = hrt_absolute_time();
			double time_elapsed = (double)(hrt_elapsed_time(&begin[j]) * 1e-6f);

			w[j] = (double)esc.esc[j].esc_rpm;
			begin[j] = hrt_absolute_time();
			i_hat[j] = (double)esc.esc[j].esc_current;
			// _currentMean[j] = updateMeanFilter(_currentMean[j], i_hat[j], _windowSize, _filterListCurrent[j]);
			// _rpmMean[j] = updateMeanFilter(_rpmMean[j], w[j], _windowSize, &_filterListRpm[j]);

			// _rpmMean_old[j] = _rpmMean[j];
			// double v_hat = (double)esc.esc[0].esc_voltage;

			w_dot_hat[j] = (double)(w[j] - w_old[j]) / time_elapsed;
			// _rpmMean_dot[j] = (double)(_rpmMean[j] - _rpmMean_old[j]) / time_elapsed;

			// parameters_update();

			thrust[j] = thrust_computation(i_hat[j], w[j], w_dot_hat[j], j);
			// thrust[j] = thrust[j];
		}
		end_all = clock();
	}

	// Example
	//  publish some data
	vehicle_thrust_estimate_s data;
	data.timestamp = hrt_absolute_time();
	data.thrust[0] = thrust[0] * thrust_scale;
	data.thrust[1] = thrust[1] * thrust_scale;
	data.thrust[2] = thrust[2] * thrust_scale;
	data.thrust[3] = thrust[3] * thrust_scale;
	data.time_elapsed = hrt_elapsed_time(&_begin_all);
	_thrust_estimate_pub.publish(data);

	perf_end(_loop_perf);
}

// Function to update the mean filter for a new data point
double ThrustEstimate::updateMeanFilter(double currentMean, double newDataPoint, int windowSize, List<currentData *>& buffer) {
	currentData *newDataNode = new currentData();
	newDataNode->data = newDataPoint;

	// Update buffer with the new data point
	buffer.add(newDataNode);

	// If the buffer size exceeds the window size, remove the oldest element
	if (static_cast<int>(buffer.size()) > windowSize) {
		currentMean -= buffer.getHead()->data;
		buffer.deleteNode(buffer.getHead());
	}

	double sum = 0.0;
	for (currentData* element : buffer) {
		sum += element->data;
	}
	currentMean = sum / static_cast<int>(buffer.size());

	return currentMean;
}

int ThrustEstimate::task_spawn(int argc, char *argv[])
{
	ThrustEstimate *instance = new ThrustEstimate();

	if (instance) {
		_object.store(instance);
		_task_id = task_id_is_work_queue;

		if (instance->init()) {
			return PX4_OK;
		}

	} else {
		PX4_ERR("alloc failed");
	}

	delete instance;
	_object.store(nullptr);
	_task_id = -1;

	return PX4_ERROR;
}

int ThrustEstimate::print_status()
{
	perf_print_counter(_loop_perf);
	perf_print_counter(_loop_interval_perf);
	return 0;
}

int ThrustEstimate::custom_command(int argc, char *argv[])
{
	return print_usage("unknown command");
}

int ThrustEstimate::print_usage(const char *reason)
{
	if (reason) {
		PX4_WARN("%s\n", reason);
	}

	PRINT_MODULE_DESCRIPTION(
		R"DESCR_STR(
### Description
Example of a simple module running thurst estimate.

)DESCR_STR");

	PRINT_MODULE_USAGE_NAME("thrust_estimate", "template");
	PRINT_MODULE_USAGE_COMMAND("start");
	PRINT_MODULE_USAGE_DEFAULT_COMMANDS();

	return 0;
}

double ThrustEstimate::compute_lambda_i(double lambda_s){
	double a = c[4];
	double b = c[4]*lambda_s + c[1];
	double _c = c[1]*(lambda_s - c[2]);
	double delta = b * b - 4 * a * _c;
	double root;
	if(delta >= 0){
		double root1 = (-b + sqrt(delta))/(2*a);
		double root2 = (-b - sqrt(delta))/(2*a);
		root = (root1 >= root2) ? root1 : root2;
	} else {
		root = -b / (2 * a);
	}
	return root;
}

double ThrustEstimate::compute_C_T(double lambda_i, double lambda_s){
	double lambda = lambda_i + lambda_s;
	return c[1]*(c[2] - lambda);
}

double ThrustEstimate::compute_kappa(double C_T){
	return d[0] + (d[1] * C_T);
}

double ThrustEstimate::compute_C_P_am_hat(double lambda_i, double lambda_s, double C_T, double kappa){
	return c[3] + C_T * ((kappa * lambda_i) + lambda_s) * c[0];
}

double ThrustEstimate::compute_mu(double vx, double vy, double _w){
	// TODO use the wind estimation
	// e_hor[0] = vx/V_h;
	// e_hor[1] = vy/V_h;
	// e_hor[2] = 0;
	return sqrt(vx*vx + vy*vy)/(_w*radius);
}

double ThrustEstimate::compute_gamma(){
	return (2*c[0]*c[1])/(N_b*I_r);
}

double ThrustEstimate::compute_azero(double lambda_i, double lambda_s, double _mu){
	double gamma = compute_gamma();
	double lambda = lambda_i + lambda_s;
	return (gamma * (c[2] * (1 + _mu*_mu) - (4 * lambda / 3))) / 8;
}

double ThrustEstimate::compute_aum(double lambda_i, double lambda_s, double _mu){
	double lambda = lambda_i + lambda_s;
	double num = 2 * _mu * ((4 * c[2])/(3 - lambda));
	double den = 1 - ((_mu*_mu)/2);
	return num/den;
}

double ThrustEstimate::compute_bum(double _mu, double azero){
	double num = (4 * _mu * azero)/3;
	double den = 1 + ((_mu*_mu)/2);
	return num/den;
}

double ThrustEstimate::compute_C_H(double lambda_i, double lambda_s, double _mu, double _azero, double _bum){
	double lambda = lambda_i + lambda_s;
	double a = c[3]/c[0];
	double b = c[2] * (lambda - _bum + (lambda * _azero));
	double _c = 2 * lambda * ((4*c[2]/3) - lambda);
	double _d = 2 * lambda * _bum;
	double e = (c[1]/2) * (b + _c - _d);
	return _mu * (a + e);
}

// iterative algorithm to converge to the optimum lambda_s
double ThrustEstimate::thrust_computation(double _i_hat, double _w, double _w_dot_hat, int index){
	double P_am_hat = (K_q[0] - ((K_q[1] * _i_hat))) * _i_hat * _w - (I_r * _w * _w_dot_hat);
	double C_P_am_t = P_am_hat / (_i_hat * _i_hat * _i_hat);
	// double C_P_am_t = P_am_hat / (_w * _w * _w);
	double lambda_s[N+1];
	double f[N+1];
	if (isnan(fabs(old_lambda_s_k[index]))){
		old_lambda_s_k[index] = 0;
	}
	lambda_s[0] = old_lambda_s_k[index] - Delta;
	int k;
	double C_T = 0;
	for(k = 0; k < N; k++){
		if(k == 1) {lambda_s[k] = old_lambda_s_k[index];}
		double lambda_i = compute_lambda_i(lambda_s[k]);
		C_T = compute_C_T(lambda_i, lambda_s[k]);
		double kappa = compute_kappa(C_T);
		double C_P_am_hat = compute_C_P_am_hat(lambda_i, lambda_s[k], C_T, kappa);
		f[k] = C_P_am_t - C_P_am_hat;
		if((k > 1) && (fabs(f[k] - f[k-1]) < epsilon)){break;}
		lambda_s[k+1] = lambda_s[k] - f[k]*((lambda_s[k] - lambda_s[k-1])/(f[k] - f[k-1]));
	}
	old_lambda_s_k[index] = lambda_s[k];
	double _thrust = C_T * _w * _w;
	if ((isnan(fabs(_thrust))) || (_thrust < -100000) || (_thrust > 100000)){
		_thrust = old_thrust[index];
	}
	return _thrust;
}

void ThrustEstimate::initialize_parameters(void){
	for(int i = 0; i < 4; i++){
		begin[i] = clock();
	}
	I_r = mass * radius * radius;
	c[4] = 2 * rho * (double) M_PI_F * c[0] * c[0];
}

extern "C" __EXPORT int thrust_estimate_main(int argc, char *argv[])
{
	return ThrustEstimate::main(argc, argv);
}
